# SPDX-FileCopyrightText: 2026 Max Mehl <https://mehl.mx>
# SPDX-License-Identifier: CC0-1.0

[project]
name = "proctr"
version = "1.0.1"
description = "Terminal UI for triaging open pull/merge requests across multiple repositories and forges"
authors = [{ name = "Max Mehl", email = "mail@mehl.mx" }]
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE"]
keywords = [
    "renovate",
    "dependabot",
    "cli",
    "tui",
    "interactive",
    "automation",
    "management",
    "dependency",
    "update",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Topic :: Software Development",
    "Topic :: Software Development :: Version Control :: Git",
    "Topic :: Utilities",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
requires-python = ">=3.11"
dependencies = [
    "jsonschema==4.26.0",
    "platformdirs==4.11.0",
    "pyyaml==6.0.3",
    "textual==8.2.8",
]

[project.urls]
Repository = "https://github.com/mxmehl/proctr"
Changelog = "https://github.com/mxmehl/proctr/blob/main/CHANGELOG.md"

[project.scripts]
proctr = "proctr:main"

[dependency-groups]
dev = ["pytest>=9.1.1", "ruff>=0.15.10", "ty>=0.0.29"]

[build-system]
requires = ["uv_build>=0.11.32,<0.12.0"]
build-backend = "uv_build"

# FORMATTING and LINTING settings
[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["ALL"]
ignore = ["T", "FBT", "LOG015", "COM812", "ERA001", "S310", "D205", "D212", "PTH123", "CPY"]
[tool.ruff.lint.extend-per-file-ignores]
"tests/*" = [
    "S101",
    "PLR",
    "PT011",
    "ANN001",
    "S105",
    "S106",
    "DTZ001",
    "D107",
    "SLF001",
    "ARG005",
    "ASYNC240",
]
"scripts/*" = ["INP001", "D103", "T201"]
[tool.ruff.lint.pydocstyle]
convention = "google"

# TY settings
[tool.ty.src]
include = ["src"]
